2023-12-20 20:01:55 [INFO] Going to loop over dir Original and counterfeit Colombian peso banknotes/COP_banknote/ds1/Train
2023-12-20 20:01:55 [INFO] Found total 12479 images to run on, 12479 train, 0 test, name list 12479, counter 12479 
2023-12-20 20:02:03 [INFO] Found total 12479 images to run on
2023-12-20 20:02:03 [INFO] 86) Finished write_index() NN model
2023-12-20 20:02:03 [INFO] Stored nn model index file train/nnf.index
2023-12-20 20:02:03 [INFO] Total time took 8175 ms
2023-12-20 20:02:03 [INFO] Found a total of 6043 fully identical images (d>0.990), which are 24.21 % of total graph edges
2023-12-20 20:02:03 [INFO] Found a total of 10153 nearly identical images(d>0.980), which are 40.68 % of total graph edges
2023-12-20 20:02:03 [INFO] Found a total of 24875 above threshold images (d>0.900), which are 99.67 % of total graph edges
2023-12-20 20:02:03 [INFO] Found a total of 1247 outlier images         (d<0.050), which are 5.00 % of total graph edges
2023-12-20 20:02:03 [INFO] Min distance found 0.446 max distance 1.000
2023-12-20 20:02:03 [INFO] Running connected components for ccthreshold 0.960000 
